### ISSUE TITLE
关于修改您的代码并开源到github

### ISSUE THREAD

**Issue by teamwong111** [BaiJiazm/SubwayTransferSystem#1]
您好，我之前clone了您的代码并做了部分修改，我想发布到github上，但我注意到您的仓库并没有表明License，所以请问我可以在我的readme中标明我借鉴了您的代码，然后将代码发布吗？

**Comment by BaiJiazm** [comment]
好呀～请自取------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;teamwong111&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月3日(星期三) 下午4:23
收件人:&nbsp;&quot;BaiJiazm/SubwayTransferSystem&quot;<SubwayTransferSystem@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[BaiJiazm/SubwayTransferSystem] 关于修改您的代码并开源到github (#1)
